// Datos de juegos y trofeos.
// Para añadir un juego nuevo, agrega un objeto más al arreglo GAMES.
const GAMES = [
  {
    id: "assassins-creed-2",
    titulo: "Assassin's Creed II",
    saga: "Assassin's Creed",
    anio: 2009,
    plataformas: "PS3 · PS4 (Ezio Collection) · Xbox 360 · PC",
    horasPlatino: 30,
    dificultad: 3,
    color: "#7c5cff",
    resumen:
      "Ezio Auditore busca venganza en la Florencia y Venecia del Renacimiento. Es uno de los platinos más queridos de la saga: no tiene multijugador, solo requiere completar la historia y varios coleccionables/desafíos secundarios, y tiene un único trofeo perdible.",
    perdibles: [
      {
        nombre: "Batiendo las alas",
        razon:
          "Hay que dar una patada a un guardia mientras vuelas en la máquina voladora de Leonardo. Solo puedes usarla durante la misión de la Secuencia 8 en la que aparece; una vez que avanzas la historia no vuelves a tener acceso a ella (salvo que tengas el DLC \"La Batalla de Forlì\", que la deja disponible libremente).",
      },
    ],
    trofeos: [
      { tier: "platino", nombre: "Maestro asesino", desc: "Desbloquear todos los demás trofeos del juego." },

      { tier: "bronce", nombre: "Nace un asesino", desc: "Volver a nacer como Ezio Auditore de Florencia." },
      { tier: "bronce", nombre: "Adiós, Abstergo", desc: "Huir de Abstergo." },

      { tier: "plata", nombre: "Bienvenido al Animus 2.0", desc: "Entrar en el Animus 2.0." },
      { tier: "plata", nombre: "El dolor de la traición", desc: "Completar la secuencia de ADN 1." },
      { tier: "plata", nombre: "Venganza", desc: "Completar la secuencia de ADN 2." },
      { tier: "plata", nombre: "El hijo sale en escena", desc: "Completar la secuencia de ADN 3." },
      { tier: "plata", nombre: "Domingo sangriento", desc: "Completar la secuencia de ADN 4." },
      { tier: "plata", nombre: "El sepulturero", desc: "Descubrir la tumba del asesino dentro de las catacumbas bajo Santa Maria Novella." },
      { tier: "plata", nombre: "Los conspiradores", desc: "Completar la secuencia de ADN 5." },
      { tier: "plata", nombre: "Un viaje inesperado", desc: "Completar la secuencia de ADN 6." },
      { tier: "plata", nombre: "El efecto sangrado", desc: "Completar el entrenamiento y volver al Animus." },
      { tier: "plata", nombre: "El mercader de Venecia", desc: "Completar la secuencia de ADN 7." },
      { tier: "plata", nombre: "Un palacio impenetrable", desc: "Completar la secuencia de ADN 8." },
      { tier: "plata", nombre: "Mascarada", desc: "Completar la secuencia de ADN 9." },
      { tier: "plata", nombre: "El hombre de Bianca", desc: "Completar la secuencia de ADN 10." },
      { tier: "plata", nombre: "El profeta", desc: "Completar la secuencia de ADN 11." },
      { tier: "plata", nombre: "La cámara", desc: "Completar la secuencia de ADN 14." },

      { tier: "oro", nombre: "Regresa un viejo amigo", desc: "Escapar del escondite." },

      { tier: "bronce", nombre: "Creador de mitos", desc: "Encontrar las 8 estatuillas en Monteriggioni." },
      { tier: "bronce", nombre: "El hombre de Vitruvio", desc: "Desbloquear los 20 fragmentos del vídeo del Sujeto 16." },
      { tier: "bronce", nombre: "Limpiador de calles", desc: "Esconder 5 cadáveres en un fardo de paja." },
      { tier: "bronce", nombre: "Batiendo las alas", desc: "Dar una patada a un guardia mientras vuelas en la máquina voladora." },
      { tier: "bronce", nombre: "El hombre de arena", desc: "Aturdir a 4 guardias a la vez arrojando arena a su rostro." },
      { tier: "bronce", nombre: "El doctor", desc: "Realizar un asesinato aéreo sobre un PNJ envenenado." },
      { tier: "bronce", nombre: "Ni un rasguño", desc: "Matar a 10 enemigos durante un conflicto, sin ser herido." },
      { tier: "bronce", nombre: "Cleptomanía", desc: "Robar 1.000 florines." },
      { tier: "bronce", nombre: "El relámpago", desc: "Correr a toda velocidad durante 100 metros." },
      { tier: "bronce", nombre: "La escoba", desc: "Atacar a 5 guardias y \"barrerlos\" a todos al mismo tiempo con un arma larga." },
      { tier: "bronce", nombre: "El gladiador veneciano", desc: "Descubrir la tumba del asesino dentro de Santa Maria della Visitazione." },
      { tier: "bronce", nombre: "Veo tu casa desde aquí", desc: "Descubrir la tumba del asesino dentro de la Torre Grossa." },
      { tier: "bronce", nombre: "Loado sea su nombre", desc: "Descubrir la tumba del asesino dentro de la Basílica de San Marcos." },
      { tier: "bronce", nombre: "Huida de la prisión", desc: "Descubrir la tumba del asesino dentro de la fortaleza de Rocca di Ravaldino." },
      { tier: "bronce", nombre: "El niño del coro", desc: "Descubrir la tumba del asesino dentro de Santa Maria del Fiore (el Duomo)." },
      { tier: "bronce", nombre: "Asesino a sueldo", desc: "Completar tu primera misión de asesinato para Lorenzo el Magnífico." },
      { tier: "bronce", nombre: "Un hombretón", desc: "Defender el honor de una mujer." },
      { tier: "bronce", nombre: "Ladrón en casa", desc: "Ganar una carrera contra los ladrones." },
      { tier: "bronce", nombre: "Muestra tus colores", desc: "Llevar la capa de los Auditore en cada ciudad." },
      { tier: "bronce", nombre: "Un manitas", desc: "Mejorar un edificio en la fortaleza." },
      { tier: "bronce", nombre: "Me gustan las vistas", desc: "Sincronizarse con 10 atalayas." },
      { tier: "bronce", nombre: "Hasta el fondo", desc: "Realizar un salto de fe desde lo alto del campanario del Giotto de Florencia." },
      { tier: "bronce", nombre: "El cartero", desc: "Interceptar al mensajero de los Borgia." },
      { tier: "bronce", nombre: "La punta del iceberg", desc: "Usar la vista de águila para encontrar un glifo oculto en el escenario." },
      { tier: "bronce", nombre: "Una pieza en el rompecabezas", desc: "Desbloquear uno de los fragmentos del vídeo del Sujeto 16." },
      { tier: "bronce", nombre: "El experto en arte", desc: "Comprar un cuadro en Florencia y en Venecia." },
      { tier: "bronce", nombre: "El señor de Monteriggioni", desc: "Conseguir el 80% del valor total de tu fortaleza." },
      { tier: "bronce", nombre: "Una armonía perfecta", desc: "Teñir tu ropa de estos colores: marfil del humedal y ébano del humedal." },
      { tier: "bronce", nombre: "En memoria de Petruccio", desc: "Conseguir todas las plumas." },
      { tier: "bronce", nombre: "Adicto a las buenas compañías", desc: "Gastar 5.000 florines en cortesanas." },
      { tier: "bronce", nombre: "El hombre del pueblo", desc: "Arrojar más de 300 florines al suelo." },
      { tier: "bronce", nombre: "La victoria requiere preparación", desc: "Conseguir todas las hojas ocultas, el equipo de bolsa y las mejoras de armadura para Ezio." },
    ],
  },

  {
    id: "devil-may-cry-hd",
    titulo: "Devil May Cry",
    saga: "Devil May Cry",
    anio: 2001,
    plataformas: "PS3 · Xbox 360 (Devil May Cry HD Collection, 2012)",
    horasPlatino: 24,
    dificultad: 8,
    color: "#c1382d",
    resumen:
      "Dante se adentra en la isla de Mallet Island para enfrentarse a Mundus y vengar a su familia. El origen de la saga, y también el platino más exigente de la colección: pide terminar el juego en la dificultad Dante Must Die, sacar un rango S en alguna misión, varios coleccionables (orbes rojos, armas, archivos de enemigos) y una partida limpia sin usar gemas amarillas.",
    perdibles: [
      {
        nombre: "Yo no he sido",
        razon:
          "Hay que terminar el juego entero sin usar ni una sola gema/orbe amarillo (las que te reviven al morir). Si usas una, esa partida ya no sirve para el trofeo y hay que reiniciar una run limpia desde cero; conviene guardarlo para una partida dedicada en dificultad Fácil una vez conozcas bien el juego.",
      },
    ],
    trofeos: [
      { tier: "platino", nombre: "Trofeo de platino", desc: "Desbloquear todos los trofeos." },
      { tier: "bronce", nombre: "¡A calentar motores!", desc: "Acaba el juego en el modo normal." },
      { tier: "plata", nombre: "¡Caliente, caliente!", desc: "Acaba el juego en el modo difícil." },
      { tier: "oro", nombre: "¡Fuegooo!", desc: "Acaba el juego en el modo Dante debe morir." },
      { tier: "oro", nombre: "El detalle marca la diferencia", desc: "Compra todas las destrezas de Dante." },
      { tier: "bronce", nombre: "¿Sabes guardar un secreto?", desc: "Supera una misión secreta." },
      { tier: "plata", nombre: "Seis secretos", desc: "Supera seis misiones secretas." },
      { tier: "oro", nombre: "Secreto en el aire", desc: "Supera todas las misiones secretas." },
      { tier: "plata", nombre: "Sensación sublime", desc: "Consigue un rango S en alguna misión." },
      { tier: "bronce", nombre: "Aracnofobia", desc: "Sobrevive a un encuentro con Phantom." },
      { tier: "bronce", nombre: "No eres un angelito", desc: "Sobrevive a un encuentro con Nelo Angelo." },
      { tier: "bronce", nombre: "Aplastado como un bicharraco", desc: "Derrota a Phantom." },
      { tier: "bronce", nombre: "Aves de presa", desc: "Sobrevive a un encuentro con Griffon." },
      { tier: "bronce", nombre: "Halo hecho añicos", desc: "Lucha contra Nelo Angelo por segunda vez e imponte." },
      { tier: "bronce", nombre: "Abstinencia", desc: "Lucha contra Griffon por segunda vez e imponte." },
      { tier: "bronce", nombre: "Con las pilas puestas", desc: "Derrota a Griffon." },
      { tier: "bronce", nombre: "Pesadillas de medianoche", desc: "Sobrevive a un encuentro con Nightmare." },
      { tier: "bronce", nombre: "Ángel caído", desc: "Derrota a Nelo Angelo." },
      { tier: "bronce", nombre: "Dulces sueños", desc: "Lucha contra Nightmare por segunda vez e imponte." },
      { tier: "bronce", nombre: "Adiós a la pesadilla", desc: "Derrota a Nightmare." },
      { tier: "bronce", nombre: "El diablo pasó por...", desc: "Derrota a Mundus." },
      { tier: "bronce", nombre: "Atónito", desc: "Realiza un combo de rango S con Alastor." },
      { tier: "bronce", nombre: "Calor infernal", desc: "Realiza un combo de rango S con Ifrit." },
      { tier: "bronce", nombre: "Tabla de contenidos", desc: "Desbloquea a todos los enemigos del menú de estado." },
      { tier: "plata", nombre: "Empollón", desc: "Desbloquea el 50% de las entradas de los enemigos del menú de estado." },
      { tier: "oro", nombre: "Eres muy transparente", desc: "Desbloquea todas las entradas de los enemigos del menú de estado." },
      { tier: "bronce", nombre: "Rojo de furia", desc: "Coge 10.000 gemas rojas." },
      { tier: "plata", nombre: "La sangre colorada", desc: "Coge 25.000 gemas rojas." },
      { tier: "oro", nombre: "Salvación", desc: "Coge 50.000 gemas rojas." },
      { tier: "bronce", nombre: "Demonio azul", desc: "Consigue una gema azul." },
      { tier: "oro", nombre: "Diablo azul", desc: "Establece al tope la barra de salud." },
      { tier: "bronce", nombre: "Recogearmas", desc: "Coge todas las armas de fuego." },
      { tier: "plata", nombre: "Yo no he sido", desc: "Acaba el juego sin usar gemas amarillas." },
      { tier: "plata", nombre: "Inalcanzable", desc: "Supera una misión sin sufrir ningún daño." },
    ],
  },

  {
    id: "devil-may-cry-2-hd",
    titulo: "Devil May Cry 2",
    saga: "Devil May Cry",
    anio: 2003,
    plataformas: "PS3 · Xbox 360 (Devil May Cry HD Collection, 2012)",
    horasPlatino: 16,
    dificultad: 3,
    color: "#3b6b8c",
    resumen:
      "Dante viaja a Vie de Marli para detener a Arius y Argosax; Lucia libra su propia campaña paralela. Se le considera el platino más accesible de la trilogía clásica: no exige rangos S difíciles ni misiones perdibles, solo terminar el juego con ambos personajes en varias dificultades y superar el Palacio Sangriento.",
    perdibles: [],
    trofeos: [
      { tier: "platino", nombre: "Trofeo de platino", desc: "Desbloquear todos los trofeos." },
      { tier: "bronce", nombre: "Las rodillas se doblarán", desc: "Acaba el juego en el modo normal con cualquier personaje." },
      { tier: "plata", nombre: "Las cabezas se inclinarán", desc: "Acaba el juego en el modo difícil con cualquier personaje." },
      { tier: "oro", nombre: "Las confesiones saldrán a la luz", desc: "Termina el juego en modo \"Debe Morir\" con cualquier personaje." },
      { tier: "plata", nombre: "Belleza desnuda", desc: "Acaba el juego en cualquier dificultad con Trish." },
      { tier: "plata", nombre: "Un secreto desvelado", desc: "Supera una misión secreta." },
      { tier: "bronce", nombre: "Sangre fresca", desc: "Pasa 1000 plantas del Palacio Sangriento." },
      { tier: "plata", nombre: "Arriendo de sangre", desc: "Pasa 5000 plantas del Palacio Sangriento." },
      { tier: "oro", nombre: "¡Más de 9000!", desc: "Pasa 9000 plantas del Palacio Sangriento." },
      { tier: "bronce", nombre: "Todo un honor", desc: "Consigue un rango S en una misión con Dante." },
      { tier: "bronce", nombre: "El cielo es el límite", desc: "Consigue un rango S en una misión con Lucia." },
      { tier: "plata", nombre: "Vita Maxima", desc: "Establece al tope la barra de salud con cualquier personaje." },
      { tier: "plata", nombre: "Magica Maxima", desc: "Establece al tope el indicador de diablo con cualquier personaje." },
      { tier: "plata", nombre: "Caeruleus Diabolus", desc: "Coge 12 fragmentos de gema azul (Dante/Lucia)." },
      { tier: "plata", nombre: "Dos mentes son mejor que una", desc: "Derrota a Tartarussian." },
      { tier: "plata", nombre: "¡A hacer un poquito el payaso!", desc: "Derrota a Orangguerra." },
      { tier: "bronce", nombre: "Sin guasa", desc: "Derrota a Jokatgulm." },
      { tier: "plata", nombre: "Ciudad del pecado", desc: "Derrota a Nefasturris." },
      { tier: "plata", nombre: "A gran profundidad", desc: "Derrota a Tateobesu." },
      { tier: "bronce", nombre: "Menudo tamaño...", desc: "Derrota a Noctpteran." },
      { tier: "plata", nombre: "Hambre de toro", desc: "Derrota a Bolverk." },
      { tier: "bronce", nombre: "Bola y cadena", desc: "Derrota a Plutonian." },
      { tier: "bronce", nombre: "No es un humano cualquiera", desc: "Derrota a Phantom." },
      { tier: "bronce", nombre: "Nunca olvides un rostro", desc: "Derrota a Trismagia." },
      { tier: "bronce", nombre: "Extinguido", desc: "Derrota al jefe final con Dante o Lucia." },
      { tier: "bronce", nombre: "¡Menudo estilo!", desc: "Realiza un combo de rango S con Dante." },
      { tier: "bronce", nombre: "En boga", desc: "Realiza un combo de rango S con Lucia." },
      { tier: "plata", nombre: "Armado y peligroso", desc: "Alcanza el nivel 3 con Lucia en cualquier espada." },
      { tier: "plata", nombre: "Carrera de armas", desc: "Alcanza el nivel 3 con Dante en cualquier arma de fuego." },
      { tier: "oro", nombre: "Avanzando paso a paso", desc: "Alcanza el nivel 3 con Dante en todas las espadas." },
      { tier: "oro", nombre: "A tope", desc: "Alcanza el nivel 3 con Lucia en todos los arsenales." },
      { tier: "plata", nombre: "Pura armonía", desc: "Coge todas las espadas con Dante." },
      { tier: "plata", nombre: "Mira esto", desc: "Coge todos los arsenales con Lucia." },
      { tier: "plata", nombre: "Cuídate, Lucia", desc: "Coge todos los corazones del demonio con Lucia." },
    ],
  },

  {
    id: "devil-may-cry-3-hd",
    titulo: "Devil May Cry 3: Dante's Awakening",
    saga: "Devil May Cry",
    anio: 2005,
    plataformas: "PS3 · Xbox 360 (Devil May Cry HD Collection, 2012)",
    horasPlatino: 50,
    dificultad: 6,
    color: "#8b2fc9",
    resumen:
      "Precuela con un Dante joven que se enfrenta a su hermano Vergil en la Torre Temen-ni-gru. Es el platino más largo y exigente de la colección: exige terminar el juego en Dante Must Die con cualquier personaje, conseguir rango S en todas las misiones y completar el Palacio Sangriento entero.",
    perdibles: [],
    trofeos: [
      { tier: "platino", nombre: "Trofeo de platino", desc: "Desbloquear todos los trofeos." },
      { tier: "bronce", nombre: "Todo un comienzo", desc: "Acaba el juego en el modo normal con cualquier personaje." },
      { tier: "plata", nombre: "Al infierno", desc: "Acaba el juego en el modo difícil con cualquier personaje." },
      { tier: "plata", nombre: "Ida y vuelta al infierno", desc: "Acaba el juego en el modo superdifícil con cualquier personaje." },
      { tier: "oro", nombre: "El infierno no es tan malo...", desc: "Acaba el juego en el modo Dante debe morir con cualquier personaje." },
      { tier: "plata", nombre: "El cielo puede esperar", desc: "Acaba el juego en el modo cielo o infierno con cualquier personaje." },
      { tier: "plata", nombre: "¿Soy el ángel de mi hermano?", desc: "Acaba el juego en cualquier dificultad como Vergil." },
      { tier: "bronce", nombre: "El peor secreto guardado", desc: "Supera una misión secreta con un personaje." },
      { tier: "oro", nombre: "Esforzarse al máximo", desc: "Supera todas las misiones secretas con un personaje." },
      { tier: "plata", nombre: "Al infierno y punto", desc: "Acaba con 100 enemigos en los créditos." },
      { tier: "bronce", nombre: "Sangre, sudor y lágrimas", desc: "Pasa 666 niveles en el Palacio Sangriento." },
      { tier: "plata", nombre: "Donante de sangre", desc: "Pasa 5000 niveles en el Palacio Sangriento." },
      { tier: "oro", nombre: "Infierno colorado", desc: "Supera el Palacio Sangriento entero." },
      { tier: "bronce", nombre: "Hecho diabólico", desc: "Consigue el rango S en una misión con cualquier personaje." },
      { tier: "oro", nombre: "Honor infernal", desc: "Consigue el rango S en todas las misiones (con cualquier personaje o dificultad)." },
      { tier: "bronce", nombre: "El mejor amigo del hombre", desc: "Derrota a Cerbero." },
      { tier: "bronce", nombre: "Lucha contra los insectos", desc: "Derrota a Gigapiés." },
      { tier: "bronce", nombre: "Problemas y más problemas", desc: "Derrota a Agni y Rudra." },
      { tier: "bronce", nombre: "Rivalidad entre hermanos", desc: "Sobrevive a un encuentro con Vergil." },
      { tier: "bronce", nombre: "Al dedillo", desc: "Derrota al Corazón de Leviatán." },
      { tier: "bronce", nombre: "Un reto inalcanzable", desc: "Derrota a Nevan." },
      { tier: "bronce", nombre: "Cuenta los segundos", desc: "Derrota a Beowulf." },
      { tier: "bronce", nombre: "Jinete duro de pelar", desc: "Derrota a Geryon." },
      { tier: "bronce", nombre: "Cariño fraternal", desc: "Lucha contra Vergil por segunda vez e imponte." },
      { tier: "bronce", nombre: "Eso no es propio de una señorita", desc: "Derrota a Lady." },
      { tier: "bronce", nombre: "Acércate a la luz", desc: "Derrota a Doppelganger." },
      { tier: "bronce", nombre: "Asilo", desc: "Derrota a Arkham." },
      { tier: "plata", nombre: "Todo un derrochador", desc: "Compra todas las armas demoníacas con Dante." },
      { tier: "plata", nombre: "¿Quién ríe ahora?", desc: "Derrota a Jester en todas sus formas." },
      { tier: "plata", nombre: "Un camino poco común", desc: "Supera todas las misiones en el modo gema amarilla." },
      { tier: "oro", nombre: "Marcador de tendencias", desc: "Alcanza el nivel más alto en todos los estilos con Dante." },
      { tier: "plata", nombre: "Lista y cargada", desc: "Alcanza el nivel más alto en un arma de fuego con Dante." },
      { tier: "plata", nombre: "Establece al tope tu salud", desc: "Establece al tope la barra de salud con Dante." },
      { tier: "plata", nombre: "Dales su merecido", desc: "Establece al tope el indicador de Devil Trigger con Dante." },
    ],
  },

  {
    id: "metal-gear-1-2-master-collection",
    titulo: "Metal Gear & Metal Gear 2: Solid Snake",
    saga: "Metal Gear",
    anio: 1987,
    plataformas: "PS4 · PS5 · Xbox Series · Switch · PC (Metal Gear Solid: Master Collection Vol. 1, 2023)",
    horasPlatino: 9,
    dificultad: 3,
    color: "#556b2f",
    resumen:
      "Remasterizaciones de los dos juegos originales de MSX2: Metal Gear (1987) y Metal Gear 2: Solid Snake (1990), donde Solid Snake se infiltra en Outer Heaven y luego en Zanzibar Land para detener a Big Boss. Es, con diferencia, el platino más corto y sencillo de toda la colección: casi todos los trofeos caen solos con la historia, solo falta superar el modo Boss Survival de cada juego.",
    perdibles: [],
    trofeos: [
      { tier: "platino", nombre: "As de trofeos de MG1 y 2", desc: "Consigue todos los trofeos." },
      { tier: "oro", nombre: "Comienza la operación Intrude N313", desc: "Empieza Metal Gear." },
      { tier: "oro", nombre: "Metal Gear TX-55", desc: "Destruye el Metal Gear." },
      { tier: "oro", nombre: "Big Boss de Outer Heaven", desc: "Derrota a Big Boss en Metal Gear." },
      { tier: "oro", nombre: "Operación Intrude N313 completada", desc: "Completa Metal Gear." },
      { tier: "oro", nombre: "Superviviente del jefe de MG1", desc: "Completa el modo Boss Survival en Metal Gear." },
      { tier: "oro", nombre: "Comienza la operación Intrude F014", desc: "Empieza Metal Gear 2." },
      { tier: "oro", nombre: "Metal Gear D", desc: "Destruye el Metal Gear D." },
      { tier: "oro", nombre: "Uno de tus admiradores", desc: "Derrota a Gray Fox." },
      { tier: "oro", nombre: "Big Boss de Zanzibar Land", desc: "Derrota a Big Boss en Metal Gear 2." },
      { tier: "plata", nombre: "Operación Intrude F014 completada", desc: "Completa Metal Gear 2." },
      { tier: "oro", nombre: "Superviviente del jefe de MG2", desc: "Completa el modo Boss Survival en Metal Gear 2." },
      { tier: "oro", nombre: "De Pe a Pa Gear 1 y 2", desc: "Lee todas las páginas del compendio de la historia." },
    ],
  },

  {
    id: "metal-gear-solid-master-collection",
    titulo: "Metal Gear Solid",
    saga: "Metal Gear",
    anio: 1998,
    plataformas: "PS4 · PS5 · Xbox Series · Switch · PC (Metal Gear Solid: Master Collection Vol. 1, 2023)",
    horasPlatino: 30,
    dificultad: 6,
    color: "#2f6690",
    resumen:
      "Solid Snake se infiltra en Shadow Moses para detener a Liquid Snake y a FOXHOUND. El Metal Gear Solid original nunca había tenido trofeos hasta esta colección: además de la historia hay que completar las 300 misiones de entrenamiento de RV y conseguir el nombre código Fox/Big Boss en una carrera contrarreloj sin fallos.",
    perdibles: [
      {
        nombre: "Bandana conseguida",
        razon:
          "Solo se consigue si aguantas todas las sesiones de tortura de Ocelot hasta el final. Es incompatible con \"Camuflaje óptico conseguido\" en la misma partida (uno excluye al otro), así que hacen falta dos partidas para tener ambos.",
      },
      {
        nombre: "Camuflaje óptico conseguido",
        razon:
          "Solo se consigue si te rindes durante la tortura de Ocelot. Es incompatible con \"Bandana conseguida\" en la misma partida (uno excluye al otro), así que hacen falta dos partidas para tener ambos.",
      },
      {
        nombre: "Nombre código de élite",
        razon:
          "Hay que terminar el juego en menos de 3 horas, sin continuar, con 4 alertas o menos, un máximo de 25 bajas (los jefes no cuentan), gastando como mucho 1 ración y guardando la partida un máximo de 80 veces, todo en dificultad Difícil o Extrema. Si fallas algún requisito, tienes que reiniciar la carrera desde cero.",
      },
      {
        nombre: "Exorcista de fotos fantasma",
        razon:
          "Necesitas encontrar la cámara fotográfica (escondida en el hangar de tanques) y usarla para fotografiar a un fantasma oculto en el escenario antes de terminar esa partida; si no la consigues o no tomas la foto a tiempo, tienes que repetirlo en otra partida.",
      },
    ],
    trofeos: [
      { tier: "platino", nombre: "As de trofeos de MGS", desc: "Consigue todos los trofeos." },
      { tier: "bronce", nombre: "Iniciando misión", desc: "Empieza una partida nueva." },
      { tier: "bronce", nombre: "vs. Revolver Ocelot", desc: "Derrota a Revolver Ocelot." },
      { tier: "bronce", nombre: "vs. Tanque M1", desc: "Destruye el tanque M1." },
      { tier: "bronce", nombre: "vs. Ninja", desc: "Derrota a Ninja." },
      { tier: "bronce", nombre: "vs. Psycho Mantis", desc: "Derrota a Psycho Mantis." },
      { tier: "plata", nombre: "vs. Sniper Wolf", desc: "Derrota a Sniper Wolf." },
      { tier: "plata", nombre: "vs. Hind D", desc: "Destruye el Hind D." },
      { tier: "oro", nombre: "vs. Sniper Wolf (revancha)", desc: "Vence en la revancha contra Sniper Wolf." },
      { tier: "oro", nombre: "vs. Vulcan Raven", desc: "Derrota a Vulcan Raven." },
      { tier: "oro", nombre: "vs. Metal Gear REX", desc: "Derrota al Metal Gear REX." },
      { tier: "oro", nombre: "vs. Liquid Snake", desc: "Derrota a Liquid Snake." },
      { tier: "bronce", nombre: "Iniciar entrenamiento de RV", desc: "Completa una misión de entrenamiento de RV." },
      { tier: "plata", nombre: "De Pe a Pa Solid", desc: "Lee todas las páginas del compendio de la historia." },
      { tier: "oro", nombre: "Bandana conseguida", desc: "Consigue la bandana." },
      { tier: "oro", nombre: "Camuflaje óptico conseguido", desc: "Consigue el camuflaje óptico." },
      { tier: "oro", nombre: "Nombre código de élite", desc: "Consigue el nombre código Fox o Big Boss." },
      { tier: "oro", nombre: "Especialista de entrenamiento de RV", desc: "Completa todas las misiones de entrenamiento de RV." },
      { tier: "oro", nombre: "Exorcista de fotos fantasma", desc: "Exorciza una foto fantasma." },
    ],
  },
];
